### ISSUE TITLE
gulp-data support?

### ISSUE THREAD

**Issue by vbud** [rogeriopvl/gulp-ejs#15]
Have you considered making this compatible with [gulp-data](https://github.com/colynb/gulp-data)?

**Comment by rogeriopvl** [comment]
Maybe. I think it might be interesting. I'm going to think about this in detail and let you know asap.

**Comment by vbud** [comment]
:+1:

**Comment by rogeriopvl** [comment]
Added support for gulp-data in v1.2.0.

Thanks!

**Comment by vbud** [comment]
Great! Thanks for the quick response and release.
