### ISSUE TITLE
 I cannot pass data when including public template

### ISSUE THREAD

**Issue by lynnic26** [rogeriopvl/gulp-ejs#55]
`<%  include('sometemplate.ejs', {foo: 'hello'})%>`
how can I implement functionality like this?

**Comment by fastest13** [comment]
It's work if 
    return gulp.src("./src/templates/*.ejs")
and don't work if
    return gulp.src("./src/**/*.ejs")

**Comment by lynnic26** [comment]
thank you @fastest13 
I'll try it later and tell you the result
