### ISSUE TITLE
Using EJS View Helpers

### ISSUE THREAD

**Issue by elliotberry** [rogeriopvl/gulp-ejs#63]
Hello,

Apologies if I'm bringing up a stupid thing, but I'm unable to get gulp to process any EJS view helpers. When I add <%= img_tag('example.png') %> to a template, for example, I get " img_tag is not defined". Same for all other view helpers. I'm able to pass variables and options in successfully, and I'm using the EJS 2.5.1. anyone else have this issue? Thanks!

**Comment by rogeriopvl** [comment]
hey @elliotberry this is not the right place for the question, but I would say that you are using a different EJS version. Since the ["official" EJS package](https://github.com/mde/ejs) does not include view helpers.
