### ISSUE TITLE
Report more details on error

### ISSUE THREAD

**Issue by mi-g** [rogeriopvl/gulp-ejs#73]
Currently, when the ejs processing fails (like from a syntax error), the generated error event only reports an error message like `Error: Could not find matching close tag for "<%="`.

It would be nice to have the file name too so the developer knows where to search for the error in case the same stream handles several ejs files. Having the line number and column would be perfect.

Ideally, those extra details should be included in separate error object fields rather than in the error message string.

**Comment by rogeriopvl** [comment]
Released in [v4.0.0](https://github.com/rogeriopvl/gulp-ejs/releases/tag/v4.0.0)
