### ISSUE TITLE
Set root in options for absolute include paths

### ISSUE THREAD

**Issue by tderkert** [rogeriopvl/gulp-ejs#80]
I can't seem to get the root option working with gulp. I get this error:
`Error: ENOENT: no such file or directory, open \'/partials/header.ejs\'`

Would be really nice to keep includes absolute and not write out the relative paths in every include.

**Comment by rogeriopvl** [comment]
hey @tderkert , sorry for taking so long to answer back :)

what do you mean the root option? Is that option available in ejs?

**Comment by tderkert** [comment]
@rogeriopvl Hi, no problem. There is option for root in [mde's ejs](https://github.com/mde/ejs#options). 

What I wanted was to set my views directory to be the root. What is the default root, if there is one?

**Comment by rogeriopvl** [comment]
@tderkert hmm I see. At first glance I would risk saying that this might be an issue with ejs itself, since gulp-ejs is just a wrapper around it. But I'll check with more detail asap.

**Comment by rogeriopvl** [comment]
@tderkert check #83 for more details. I'll be fixing this issue ASAP.

**Comment by tderkert** [comment]
@rogeriopvl Great!

**Comment by rogeriopvl** [comment]
@tderkert this should now be fixed in `v3.0.0`, please update your `package.json` accordingly.
