### ISSUE TITLE
Problem with root option

### ISSUE THREAD

**Issue by Nejik** [rogeriopvl/gulp-ejs#83]
Hello, first of all thanks for the plugin. When i'm trying to set root option via options, seems that ejs don't get it. I'm started to search about this problem and found that https://github.com/mde/ejs/issues/221

Some options blacklisted from opts-in-data and root options seems too :( https://github.com/mde/ejs/releases/tag/v2.5.3

Suppose that now we need third parameter with options for ejs.
Or maybe i misunderstand something?

**Comment by rogeriopvl** [comment]
Hey @Nejik , thanks for the feedback.

As far as I understand, yes `gulp-ejs` now needs to send data do `ejs` with options separated from template variables.

I'll be fixing this ASAP.

**Comment by rogeriopvl** [comment]
@Nejik this should now be fixed in `v3.0.0`, please update your `package.json` accordingly.
